apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: auth-secrets
  namespace: auth
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/59413000494/secrets/AUTH_SECRET/versions/latest"
        path: "gotrue_jwt_secret"
      - resourceName: "projects/59413000494/secrets/GOOGLE_OAUTH_SECRET/versions/latest"
        path: "google_oauth_secret"
      - resourceName: "projects/59413000494/secrets/AUTH_DB_ADMIN_PASSWORD/versions/latest"
        path: "db_password"