apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- auth-vpa.yaml

namespace: solomon

namePrefix: dev-

patches:
- path: patch.yaml

labels:
- includeSelectors: true
  pairs:
    environment: dev
    tier: dev

configMapGenerator:
- behavior: merge
  literals:
  - GOTRUE_LOG_LEVEL=debug
  - DB_NAME=postgres_auth_dev
  - API_EXTERNAL_URL=https://dev.solomonauth.com/
  - GOTRUE_SITE_URL=https://dev.solomonauth.com/
  - GOTRUE_EXTERNAL_GOOGLE_REDIRECT_URI=https://dev.solomonauth.com/callback
  - GOTRUE_URI_ALLOW_LIST=http://localhost:5173/auth/callback,https://dev.insidec.org/auth/callback
  name: auth-generated-config
images:
- name: ghcr.io/danielfloresdiaz/auth
  newName: ghcr.io/danielfloresdiaz/auth
  newTag: 0.0.2
