apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: solomon
  name: auth-deployment
spec:
  selector:
    matchLabels:
      environment: dev
  template:
    metadata:
      labels:
        environment: dev
    spec:
      containers:
        - name: auth-container
          resources:
            requests:
              cpu: "20m"
              memory: "16Mi"
            limits:
              cpu: "40m"
              memory: "32Mi"
        - name: cloudsql-proxy
          resources:
            requests:
              cpu: "125m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"