apiVersion: v1
kind: Service
metadata:
  name: auth-service-prod
  namespace: auth
  labels:
    service: auth-service-prod
    environment: prod
spec:
  type: ClusterIP
  ports:
    - port: 9999
      targetPort: 9999
      protocol: TCP
  selector:
    app: auth
    environment: prod
