apiVersion: v1
kind: Service
metadata:
  name: auth-service-dev
  namespace: auth
  labels:
    service: auth-service-dev
    environment: dev
spec:
  type: ClusterIP
  ports:
    - port: 9999
      targetPort: 9999
      protocol: TCP
  selector:
    app: auth
    environment: dev
